import {theme} from './theme';
export const groups = {
  'Languages': ['Python', 'JavaScript', 'C++', 'C'],
  'AI & ML': ['PyTorch', 'Scikit-learn', 'YOLOv8', 'OpenCV', 'Flower', 'LLMs', 'AI Agents', 'MCP'],
  'Web & backend': ['React', 'Node.js', 'Express.js', 'FastAPI', 'REST APIs', 'Electron'],
  'Cloud & tools': ['AWS EC2', 'IAM', 'AWS CLI', 'Linux', 'SSH', 'PM2', 'Git', 'Mypy', 'Pytest'],
  'Databases': ['MongoDB', 'MySQL', 'SQLite', 'DynamoDB'],
  'Data & analytics': ['Pandas', 'NumPy', 'Power BI', 'Tableau', 'Excel', 'PyMuPDF'],
};
export const projects = [
  {name:'A.R.E.S',subtitle:'Autonomous Response & Emergency Surveillance',category:'COMPUTER VISION · FEDERATED LEARNING',year:'2025–2026',role:'Lead Engineer · Final Year Project',description:'Privacy-preserving surveillance across distributed CCTV streams. Locally trained models work together to detect theft, fighting, vandalism, and weapons without transferring raw footage.',result:'83.9% detection accuracy',detail:'Improved accuracy from 73.8% to 83.9% across four simulated edge clients, with alert generation in under two seconds.',tags:['Python','YOLOv8','Flower','FastAPI','OpenCV','SQLite','Electron'],glyph:'◎'},
  {name:'MentorOS',subtitle:'An AI companion for software engineering',category:'AI AGENTS · DEVELOPER TOOLS',year:'2026',role:'Backend Contributor · Collaborative Project',description:'An LLM-powered development assistant with agent orchestration, memory handling, and Model Context Protocol integrations for multi-step reasoning and tool use.',result:'Model-agnostic architecture',detail:'Configuration and memory modules support Ollama, OpenAI, Anthropic, and OpenRouter backends.',tags:['Python','MCP','LLMs','Git','Pytest'],glyph:'⌘'},
  {name:'Browniebees',subtitle:'Cloud-native e-commerce platform',category:'FULL STACK · CLOUD INFRASTRUCTURE',year:'2025',role:'Full Stack / Cloud Engineer · Personal Project',description:'An end-to-end e-commerce application with a Node.js API, AWS infrastructure, and production operations, built and deployed independently.',result:'From API to AWS deployment',detail:'Configured IAM, security groups, SSH access, PM2 process management, and Git-based deployment workflows.',tags:['Node.js','AWS EC2','DynamoDB','Linux','PM2'],glyph:'▦'},
  {name:'Business Performance',subtitle:'Retail analytics & interactive dashboards',category:'DATA ANALYTICS · BUSINESS INTELLIGENCE',year:'2024',role:'Data Analyst · Personal Project',description:'Interactive retail dashboards that turn sales records into revenue trends, regional comparisons, and product-level insights.',result:'10,000+ records analyzed',detail:'An end-to-end workflow covering data cleaning, modeling, visualization, and stakeholder-facing KPI reporting.',tags:['Power BI','Tableau','Excel'],glyph:'↗'},
];
export function tileImage(label, index=0) {
 const safe=label.replaceAll('&','&amp;');
 return 'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="260" height="160" viewBox="0 0 260 160"><text x="130" y="73" text-anchor="middle" fill="${theme.accent}" font-family="monospace" font-size="38">${['{ }','◈','⌘','⎔','⌁'][index%5]}</text><text x="130" y="122" text-anchor="middle" fill="${theme.text}" font-family="Arial" font-size="20">${safe}</text></svg>`);
}
export const projectImages=projects.map((p,i)=>({src:'data:image/svg+xml,'+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="640" height="760"><defs><pattern id="g" width="40" height="40" patternUnits="userSpaceOnUse"><path d="M40 0H0V40" fill="none" stroke="${theme.accent}" stroke-opacity=".15"/></pattern></defs><rect width="640" height="760" fill="${theme.surface}"/><rect width="640" height="760" fill="url(#g)"/><circle cx="320" cy="270" r="150" fill="none" stroke="${theme.accent}"/><circle cx="320" cy="270" r="125" fill="none" stroke="${theme.accent}" stroke-dasharray="3 15"/><text x="320" y="320" text-anchor="middle" font-family="Arial" font-size="150" fill="${theme.text}">${p.glyph}</text><text x="42" y="60" fill="${theme.accent}" font-family="monospace" font-size="18">PROJECT 0${i+1} / ${p.year}</text><text x="42" y="530" fill="${theme.text}" font-family="Arial" font-size="${i===3?40:57}">${p.name}</text><text x="42" y="588" fill="${theme.accent}" font-family="monospace" font-size="17">${p.category.replaceAll('&','&amp;')}</text><path d="M42 630H598" stroke="${theme.accent}" stroke-opacity=".4"/><text x="42" y="690" fill="${theme.text}" font-family="Arial" font-size="23">${p.result}</text></svg>`),alt:p.name}));
